# - name: 'notify vercel'

#   on:
#     repository_dispatch:
#       - 'vercel.deployment.success'

#   jobs:
#     run-vercel-status:
#       steps:

#         - uses: 'vercel/repository-dispatch/actions/status@v1'
#           with:
#             name: Vercel - nu-be-au-exc: lint